AllCops:
  Exclude:
    - Vagrantfile
    - Thorfile

LineLength:
  Enabled: false
BlockLength:
  Enabled: false
HashSyntax:
  Enabled: false
Documentation:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
NumericLiterals:
  Enabled: false
HashSyntax:
  Enabled: false
BracesAroundHashParameters:
  Enabled: false
IndentHash:
  Enabled: false
