name             'java_libs'
maintainer       'Rakuten Inc.'
maintainer_email 'ops@rakops.com'
license          'Apache 2.0'
description      'Provides Java-related LWRPs and HWRPs'
version          '0.8.0'
