name             "java-libraries"
maintainer       "Socrata, Inc."
maintainer_email "chefs@socrata.com"
license          "Apache 2.0"
description      "Provides Java-related LWRPs and HWRPs"
version          "0.2.1"
